# Generated by Django 3.2.5 on 2021-07-05 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, verbose_name='Food Name')),
                ('food_price', models.FloatField(verbose_name='Price ($)')),
                ('food_type', models.CharField(max_length=255, verbose_name='Type')),
                ('food_content', models.CharField(max_length=255, verbose_name='Ingredients')),
                ('veg_or_non', models.BooleanField(default=False, verbose_name='Vegeterian')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount (%)')),
                ('tax', models.IntegerField(default=5, verbose_name='Tax (%)')),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.food')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False, verbose_name='Delivered')),
                ('food_orders', models.ManyToManyField(to='modelapp.UserFoodOrder')),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'Basic User'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TotalFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_orders', models.IntegerField(default=0, verbose_name='No of Orders for this food')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.food')),
            ],
        ),
    ]
